# Dependabot schedule managed by https://github.com/westerveltco/web-dependabot-config
# Updates: 2nd Tuesday of each month at ~9am CT
# Schedule: https://crontab.guru/#0_14_8-14_*_2
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: cron
      cronjob: 0 14 8-14 * 2
    labels:
      - "ðŸ¤– dependabot"
    groups:
      gha:
        patterns:
          - "*"
    cooldown:
      default-days: 7
